### PR TITLE
Updated README and removed package-lock.json

### PR DESCRIPTION
**Pull request by p1ho**
Updated README.md (with badges) so it's ready to be published on npm.
Removed package-lock.json and added it to .gitignore

I'm trying to figure out how to approach coveralls, is **[grunt](https://github.com/pimterry/grunt-coveralls)** a good choice?

### CODE REVIEW

**Review by zrrrzzt — APPROVED** [review]
Very close to release :-)

For coverage I usually install `nyc` and `coveralls` as dependencies and adds this to `scripts` in `package.json`

```JavaScript
"coverage": "nyc ava",
"coveralls": "nyc ava && nyc report --reporter=lcov && cat coverage/lcov.info | coveralls",
```

So for a quick, local check I do: `$ npm run coverage` and coveralls is added to `.travis.yml`

**Comment by p1ho** [comment]
Will do! To make sure I'm doing things proper, I will request your review again after I'm done.

**Comment by p1ho** [comment]
I've updated the `package.json` and `.gitignore` accordingly

the scripts `coverage` and `coverall` both ran fine on my machine.
I also checked on [coveralls.io](https://coveralls.io/github/p1ho/site-validator-cli) and the coverage score can be seen (I can live with 80%)

I'm not completely sure, but I'm guessing after merging this to master branch, I checkout to master branch on my local machine and run `npm run coveralls` to generate the score for the master branch (which would update the badge)?

**Review by zrrrzzt — APPROVED** [review]
Looks good.

Just checking: You have opened an account at [Coveralls](https://coveralls.io/) ?

**Comment by p1ho** [comment]
Yes, I have.
[https://coveralls.io/github/p1ho/site-validator-cli](https://coveralls.io/github/p1ho/site-validator-cli)

Once I merge this, is this ready to be published?

**Comment by zrrrzzt** [comment]
Sure! Just release it 🚀 

Happy launch day :-)

**Comment by p1ho** [comment]
Thank you for all your help! This has been a valuable experience for me!

**Comment by zrrrzzt** [comment]
My pleasure :-)

Welcome to the world of open source maintainers on npm. I'll link to this module from my own projects on next release. In time I might deprecate html-validator-cli as well in favour of this.

Great job!

**Comment by p1ho** [comment]
Thank you!!

There was a minor setback #42 (facepalm)
in a fit of panic I pulled it from npm, so I'll need to wait 24 hours before I can publish again.
This was my bad, but it was very educational

**Comment by zrrrzzt** [comment]
Best way to learn is the hard way ;-)
So next time just fix, update version and publish again.

**Pull request merged**
